server:
  port: 8080

spring:
  redis:
#    Redis服务端主机地址
    host: 192.168.2.128
#    服务端端口号
    port: 6379
#    服务端连接密码
    password: 12345
    jedis:
#      Jedis连接池配置
      pool:
#        最大连接数
        max-active: 10
#        最大空闲连接数
        max-idle: 6
#        最小空闲连接数
        min-idle: 2
#        最大阻塞等待时间
        max-wait: 10000
#    连接超时时间(ms)
    timeout: 2000